import { ICity } from '@/types/novaPoshta.t';

// Uncomments the main cities
export const regionalCitiesData: ICity[] = [
  {
    Description: 'Київ',
    Present: 'м. Київ, Київська обл.',
    Warehouses: 9168,
    MainDescription: 'Київ',
    Area: 'Київська',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e718a680-4b33-11e4-ab6d-005056801329',
    DeliveryCity: '8d5a980d-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },
  {
    Description: 'Харків',
    Present: 'м. Харків, Харківська обл.',
    Warehouses: 2176,
    MainDescription: 'Харків',
    Area: 'Харківська',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e71f8842-4b33-11e4-ab6d-005056801329',
    DeliveryCity: 'db5c88e0-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },

  {
    Description: 'Одеса',
    Present: 'м. Одеса, Одеська обл.',
    Warehouses: 2079,
    MainDescription: 'Одеса',
    Area: 'Одеська',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e71c2a15-4b33-11e4-ab6d-005056801329',
    DeliveryCity: 'db5c88d0-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },
  {
    Description: 'Дніпро',
    Present: 'м. Дніпро, Дніпропетровська обл.',
    Warehouses: 3410,
    MainDescription: 'Дніпро',
    Area: 'Дніпропетровська',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e717110a-4b33-11e4-ab6d-005056801329',
    DeliveryCity: 'db5c88f0-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },
  {
    Description: 'Запоріжжя',
    Present: 'м. Запоріжжя, Запорізька обл.',
    Warehouses: 1605,
    MainDescription: 'Запоріжжя',
    Area: 'Запорізька',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e717bce9-4b33-11e4-ab6d-005056801329',
    DeliveryCity: 'db5c88c6-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },
  {
    Description: 'Львів',
    Present: 'м. Львів, Львівська обл.',
    Warehouses: 2880,
    MainDescription: 'Львів',
    Area: 'Львівська',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e71abb60-4b33-11e4-ab6d-005056801329',
    DeliveryCity: 'db5c88f5-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },
  {
    Description: 'Чернігів',
    Present: 'м. Чернігів, Чернігівська обл.',
    Warehouses: 550,
    MainDescription: 'Чернігів',
    Area: 'Чернігівська',
    Region: '',
    SettlementTypeCode: 'м.',
    Ref: 'e71feb5c-4b33-11e4-ab6d-005056801329',
    DeliveryCity: 'db5c897c-391c-11dd-90d9-001a92567626',
    AddressDeliveryAllowed: true,
    StreetsAvailability: true,
    ParentRegionTypes: 'область',
    ParentRegionCode: 'обл.',
    RegionTypes: '',
    RegionTypesCode: '',
  },
  // {
  //   Description: 'Житомир',
  //   Present: 'м. Житомир, Житомирська обл.',
  //   Warehouses: 473,
  //   MainDescription: 'Житомир',
  //   Area: 'Житомирська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e717a3d0-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c88c4-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },

  // {
  //   Description: 'Вінниця',
  //   Present: 'м. Вінниця, Вінницька обл.',
  //   Warehouses: 1004,
  //   MainDescription: 'Вінниця',
  //   Area: 'Вінницька',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71629ab-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c88de-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },

  // {
  //   Description: 'Полтава',
  //   Present: 'м. Полтава, Полтавська обл.',
  //   Warehouses: 819,
  //   MainDescription: 'Полтава',
  //   Area: 'Полтавська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71d006d-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c8892-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Черкаси',
  //   Present: 'м. Черкаси, Черкаська обл.',
  //   Warehouses: 492,
  //   MainDescription: 'Черкаси',
  //   Area: 'Черкаська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71fe3ca-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c8902-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Рівне',
  //   Present: 'м. Рівне, Рівненська обл.',
  //   Warehouses: 603,
  //   MainDescription: 'Рівне',
  //   Area: 'Рівненська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71d65e1-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c896a-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Тернопіль',
  //   Present: 'м. Тернопіль, Тернопільська обл.',
  //   Warehouses: 495,
  //   MainDescription: 'Тернопіль',
  //   Area: 'Тернопільська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71efc6a-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c8900-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Луцьк',
  //   Present: 'м. Луцьк, Волинська обл.',
  //   Warehouses: 361,
  //   MainDescription: 'Луцьк',
  //   Area: 'Волинська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71ab70b-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c893b-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Івано-Франківськ',
  //   Present: 'м. Івано-Франківськ, Івано-Франківська обл.',
  //   Warehouses: 375,
  //   MainDescription: 'Івано-Франківськ',
  //   Area: 'Івано-Франківська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e7182b3c-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c8904-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Хмельницький',
  //   Present: 'м. Хмельницький, Хмельницька обл.',
  //   Warehouses: 567,
  //   MainDescription: 'Хмельницький',
  //   Area: 'Хмельницька',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71f8e8f-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c88ac-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Ужгород',
  //   Present: 'м. Ужгород, Закарпатська обл.',
  //   Warehouses: 182,
  //   MainDescription: 'Ужгород',
  //   Area: 'Закарпатська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71f4773-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'e221d627-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Чернівці',
  //   Present: 'м. Чернівці, Чернівецька обл.',
  //   Warehouses: 460,
  //   MainDescription: 'Чернівці',
  //   Area: 'Чернівецька',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71fe717-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'e221d642-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Кропивницький',
  //   Present: 'м. Кропивницький, Кіровоградська обл.',
  //   Warehouses: 302,
  //   MainDescription: 'Кропивницький',
  //   Area: 'Кіровоградська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e718b361-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c891b-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Суми',
  //   Present: 'м. Суми, Сумська обл.',
  //   Warehouses: 276,
  //   MainDescription: 'Суми',
  //   Area: 'Сумська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71e73be-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c88e5-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Херсон',
  //   Present: 'м. Херсон, Херсонська обл.',
  //   Warehouses: 453,
  //   MainDescription: 'Херсон',
  //   Area: 'Херсонська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71f8b5f-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c88cc-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
  // {
  //   Description: 'Миколаїв',
  //   Present: 'м. Миколаїв, Миколаївська обл.',
  //   Warehouses: 780,
  //   MainDescription: 'Миколаїв',
  //   Area: 'Миколаївська',
  //   Region: '',
  //   SettlementTypeCode: 'м.',
  //   Ref: 'e71b108c-4b33-11e4-ab6d-005056801329',
  //   DeliveryCity: 'db5c888c-391c-11dd-90d9-001a92567626',
  //   AddressDeliveryAllowed: true,
  //   StreetsAvailability: true,
  //   ParentRegionTypes: 'область',
  //   ParentRegionCode: 'обл.',
  //   RegionTypes: '',
  //   RegionTypesCode: '',
  // },
];
